FROM python:3.10-slim

WORKDIR /app

# Копируем зависимости
COPY kafka_producer/requirements.txt .

# Устанавливаем Python зависимости
RUN pip install --no-cache-dir -r requirements.txt

# Копируем код продюсера
COPY kafka_producer/ ./

# Создаем пользователя для безопасности
RUN useradd -m -u 1000 producer && chown -R producer:producer /app
USER producer

CMD ["python", "-m", "main"]
