# Generated by Django 4.2.27 on 2026-02-08 14:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ZigbeeDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Уникальный ID')),
                ('ieee_address', models.CharField(help_text='Уникальный физический адрес устройства (16-ричный)', max_length=23, unique=True, verbose_name='IEEE адрес')),
                ('nwk_address', models.CharField(blank=True, help_text='Короткий сетевой адрес устройства', max_length=6, null=True, verbose_name='Сетевой адрес')),
                ('friendly_name', models.CharField(help_text='Человеко-читаемое имя устройства', max_length=100, verbose_name='Имя устройства')),
                ('device_type', models.CharField(choices=[('temperature_humidity', 'Температура/Влажность'), ('motion', 'Датчик движения'), ('contact', 'Контактный датчик'), ('switch', 'Выключатель'), ('socket', 'Розетка'), ('light', 'Лампа'), ('gas', 'Датчик газа'), ('water', 'Датчик протечки воды'), ('vibration', 'Датчик вибрации'), ('button', 'Кнопка'), ('custom', 'Кастомное устройство')], default='custom', max_length=50, verbose_name='Тип устройства')),
                ('model', models.CharField(blank=True, help_text='Производитель и модель (например: Tuya ZG-227ZL)', max_length=100, null=True, verbose_name='Модель устройства')),
                ('manufacturer', models.CharField(blank=True, max_length=100, null=True, verbose_name='Производитель')),
                ('status', models.CharField(choices=[('online', 'В сети'), ('offline', 'Не в сети'), ('unknown', 'Неизвестно'), ('paired', 'Сопряжено'), ('interviewing', 'Опрашивается'), ('configuring', 'Настраивается'), ('error', 'Ошибка')], default='unknown', max_length=50, verbose_name='Статус устройства')),
                ('battery_status', models.CharField(choices=[('critical', 'Критический (<10%)'), ('low', 'Низкий (10-30%)'), ('medium', 'Средний (30-70%)'), ('high', 'Высокий (70-100%)'), ('unknown', 'Неизвестно')], default='unknown', max_length=50, verbose_name='Статус батареи')),
                ('battery_level', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Уровень батареи (%)')),
                ('link_quality', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(255)], verbose_name='Качество связи (LQI)')),
                ('voltage', models.FloatField(blank=True, null=True, verbose_name='Напряжение (V)')),
                ('last_seen', models.DateTimeField(blank=True, help_text='Время последнего получения данных от устройства', null=True, verbose_name='Последний контакт')),
                ('first_seen', models.DateTimeField(auto_now_add=True, verbose_name='Первый контакт')),
                ('age_days', models.IntegerField(default=0, editable=False, verbose_name='Возраст (дней)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('is_simulated', models.BooleanField(default=False, verbose_name='Симулированное')),
                ('is_permitted_to_join', models.BooleanField(default=False, verbose_name='Разрешено присоединение')),
                ('configuration', models.JSONField(blank=True, default=dict, help_text='JSON с настройками устройства (калибровка, интервалы и т.д.)', verbose_name='Конфигурация устройства')),
                ('capabilities', models.JSONField(blank=True, default=list, help_text='Список поддерживаемых возможностей', verbose_name='Возможности устройства')),
                ('firmware_version', models.CharField(blank=True, max_length=50, null=True, verbose_name='Версия прошивки')),
                ('hardware_version', models.CharField(blank=True, max_length=50, null=True, verbose_name='Версия аппаратного обеспечения')),
                ('software_build_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID сборки ПО')),
                ('date_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Дата производства')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='locations.location', verbose_name='Локация')),
            ],
            options={
                'verbose_name': 'Zigbee устройство',
                'verbose_name_plural': 'Zigbee устройства',
                'ordering': ['-last_seen', 'friendly_name'],
            },
        ),
        migrations.CreateModel(
            name='SensorMeasurement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('generated_time', models.DateTimeField(help_text='Время, когда измерение было сгенерировано устройством', verbose_name='Время измерения на устройстве')),
                ('receive_time', models.DateTimeField(auto_now_add=True, verbose_name='Время получения системой')),
                ('temperature', models.FloatField(blank=True, null=True, verbose_name='Температура (°C)')),
                ('humidity', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Влажность (%)')),
                ('pressure', models.FloatField(blank=True, null=True, verbose_name='Давление (hPa)')),
                ('occupancy', models.BooleanField(blank=True, null=True, verbose_name='Обнаружено движение')),
                ('illuminance', models.FloatField(blank=True, null=True, verbose_name='Освещенность (lux)')),
                ('illuminance_lux', models.FloatField(blank=True, null=True, verbose_name='Освещенность (lux)')),
                ('state', models.CharField(blank=True, choices=[('ON', 'Включено'), ('OFF', 'Выключено')], max_length=10, null=True, verbose_name='Состояние')),
                ('power', models.FloatField(blank=True, null=True, verbose_name='Мощность (W)')),
                ('voltage_sensor', models.FloatField(blank=True, null=True, verbose_name='Напряжение (V)')),
                ('current', models.FloatField(blank=True, null=True, verbose_name='Ток (A)')),
                ('energy', models.FloatField(blank=True, null=True, verbose_name='Потребленная энергия (kWh)')),
                ('linkquality', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(255)], verbose_name='Качество связи')),
                ('battery', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Батарея (%)')),
                ('raw_data', models.JSONField(blank=True, default=dict, help_text='Полные данные в формате JSON', verbose_name='Исходные данные')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Обработано')),
                ('has_anomaly', models.BooleanField(default=False, verbose_name='Аномалия')),
                ('anomaly_score', models.FloatField(default=0.0, verbose_name='Оценка аномальности')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='devices.zigbeedevice', verbose_name='Устройство')),
            ],
            options={
                'verbose_name': 'Измерение сенсора',
                'verbose_name_plural': 'Измерения сенсоров',
                'ordering': ['-generated_time'],
            },
        ),
        migrations.CreateModel(
            name='DeviceGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Название группы')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('devices', models.ManyToManyField(blank=True, related_name='groups', to='devices.zigbeedevice', verbose_name='Устройства')),
            ],
            options={
                'verbose_name': 'Группа устройств',
                'verbose_name_plural': 'Группы устройств',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DeviceEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('device_joined', 'Устройство присоединилось'), ('device_announce', 'Устройство объявилось'), ('device_interview', 'Опрос устройства'), ('device_leave', 'Устройство отключилось'), ('device_message', 'Сообщение устройства'), ('device_error', 'Ошибка устройства'), ('command_sent', 'Команда отправлена'), ('command_received', 'Команда получена'), ('battery_low', 'Низкий заряд батареи'), ('connection_lost', 'Потеряно соединение'), ('connection_restored', 'Соединение восстановлено'), ('state_change', 'Изменение состояния'), ('alarm', 'Тревога')], max_length=50, verbose_name='Тип события')),
                ('severity', models.CharField(choices=[('info', 'Информация'), ('warning', 'Предупреждение'), ('error', 'Ошибка'), ('critical', 'Критическая ошибка')], default='info', max_length=50, verbose_name='Важность')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время события')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='Данные события')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Решено')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Время решения')),
                ('resolution_notes', models.TextField(blank=True, verbose_name='Заметки по решению')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='devices.zigbeedevice', verbose_name='Устройство')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Решено кем')),
            ],
            options={
                'verbose_name': 'Событие устройства',
                'verbose_name_plural': 'События устройств',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DeviceConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('polling_interval', models.IntegerField(default=300, help_text='Интервал между опросами устройства', verbose_name='Интервал опроса (сек)')),
                ('report_interval', models.IntegerField(default=60, help_text='Интервал отправки отчетов устройством', verbose_name='Интервал отчетов (сек)')),
                ('temperature_calibration', models.FloatField(default=0.0, help_text='Коррекция температуры в °C', verbose_name='Калибровка температуры')),
                ('humidity_calibration', models.FloatField(default=0.0, help_text='Коррекция влажности в %', verbose_name='Калибровка влажности')),
                ('pressure_calibration', models.FloatField(default=0.0, help_text='Коррекция давления в hPa', verbose_name='Калибровка давления')),
                ('temperature_min', models.FloatField(blank=True, help_text='Нижний порог тревоги', null=True, verbose_name='Минимальная температура')),
                ('temperature_max', models.FloatField(blank=True, help_text='Верхний порог тревоги', null=True, verbose_name='Максимальная температура')),
                ('humidity_min', models.FloatField(blank=True, help_text='Нижний порог тревоги', null=True, verbose_name='Минимальная влажность')),
                ('humidity_max', models.FloatField(blank=True, help_text='Верхний порог тревоги', null=True, verbose_name='Максимальная влажность')),
                ('enable_alerts', models.BooleanField(default=True, verbose_name='Включить уведомления')),
                ('enable_logging', models.BooleanField(default=True, verbose_name='Включить логирование')),
                ('retention_days', models.IntegerField(default=90, verbose_name='Хранение данных (дней)')),
                ('advanced_config', models.JSONField(blank=True, default=dict, verbose_name='Расширенная конфигурация')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config', to='devices.zigbeedevice', verbose_name='Устройство')),
            ],
            options={
                'verbose_name': 'Конфигурация устройства',
                'verbose_name_plural': 'Конфигурации устройств',
            },
        ),
        migrations.AddIndex(
            model_name='zigbeedevice',
            index=models.Index(fields=['ieee_address'], name='devices_zig_ieee_ad_200d62_idx'),
        ),
        migrations.AddIndex(
            model_name='zigbeedevice',
            index=models.Index(fields=['status'], name='devices_zig_status_b68b1a_idx'),
        ),
        migrations.AddIndex(
            model_name='zigbeedevice',
            index=models.Index(fields=['device_type'], name='devices_zig_device__f42c96_idx'),
        ),
        migrations.AddIndex(
            model_name='zigbeedevice',
            index=models.Index(fields=['battery_status'], name='devices_zig_battery_9586bc_idx'),
        ),
        migrations.AddIndex(
            model_name='zigbeedevice',
            index=models.Index(fields=['last_seen'], name='devices_zig_last_se_841408_idx'),
        ),
        migrations.AddIndex(
            model_name='sensormeasurement',
            index=models.Index(fields=['device', 'generated_time'], name='devices_sen_device__62f06e_idx'),
        ),
        migrations.AddIndex(
            model_name='sensormeasurement',
            index=models.Index(fields=['generated_time'], name='devices_sen_generat_bb8ed4_idx'),
        ),
        migrations.AddIndex(
            model_name='sensormeasurement',
            index=models.Index(fields=['temperature'], name='devices_sen_tempera_92cf5b_idx'),
        ),
        migrations.AddIndex(
            model_name='sensormeasurement',
            index=models.Index(fields=['humidity'], name='devices_sen_humidit_e4c091_idx'),
        ),
        migrations.AddIndex(
            model_name='sensormeasurement',
            index=models.Index(fields=['has_anomaly'], name='devices_sen_has_ano_251b24_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceevent',
            index=models.Index(fields=['device', 'timestamp'], name='devices_dev_device__68810a_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceevent',
            index=models.Index(fields=['event_type'], name='devices_dev_event_t_33d4ff_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceevent',
            index=models.Index(fields=['severity'], name='devices_dev_severit_7a0374_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceevent',
            index=models.Index(fields=['is_resolved'], name='devices_dev_is_reso_2e1485_idx'),
        ),
    ]
