# Generated by Django 4.2.28 on 2026-02-08 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceStats',
            fields=[
                ('ieee_address', models.CharField(max_length=23, primary_key=True, serialize=False, verbose_name='IEEE адрес')),
                ('measurement_count', models.BigIntegerField(verbose_name='Количество измерений')),
                ('first_measurement', models.DateTimeField(verbose_name='Первое измерение')),
                ('last_measurement', models.DateTimeField(verbose_name='Последнее измерение')),
                ('avg_battery', models.FloatField(blank=True, null=True, verbose_name='Средний заряд батареи (%)')),
                ('avg_link_quality', models.FloatField(blank=True, null=True, verbose_name='Среднее качество связи')),
                ('max_latency_seconds', models.FloatField(blank=True, null=True, verbose_name='Максимальная задержка (сек)')),
            ],
            options={
                'verbose_name': 'Статистика устройства',
                'verbose_name_plural': 'Статистика устройств',
                'db_table': 'device_stats',
                'ordering': ['-last_measurement'],
                'managed': False,
            },
        ),
    ]
