apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    database: zigbee_monitoring
    user: zigbeeser
    secureJsonData:
      password: zigbeessword
    jsonData:
      sslmode: "disable"
      timescaledb: true
      postgresVersion: 1600
      tlsAuth: false
      tlsConfigurationMethod: "file-path"
      tlsSkipVerify: true
      maxOpenConns: 100
      maxIdleConns: 100
      connMaxLifetime: 14400
    isDefault: true
    editable: true
    version: 1
    uid: "postgres-ds"
