{
 "title": "Zigbee Датчики - Мониторинг",
 "tags": [
  "zigbee",
  "iot",
  "sensors"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Текущая температура",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n\tcoalesce(zd.friendly_name, lm.ieee_address) AS \"metric\",\n\t(lm.data->>'temperature')::float AS temperature\n\nFROM public.latest_measurements AS lm\nleft join devices_zigbeedevice zd on zd.ieee_address = lm.ieee_address\nORDER BY zd.created_at asc\n"
    }
   ]
  },
  {
   "title": "Температура",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT\n    sm.generated_time AS \"time\",\n    coalesce(zd.friendly_name, sm.ieee_address) AS \"metric\",\n    (sm.data->'temperature')::float AS temperature\nFROM public.sensor_measurements AS sm\nleft join devices_zigbeedevice zd on zd.ieee_address = sm.ieee_address\nWHERE $__timeFilter(sm.generated_time)\nORDER BY sm.generated_time ASC"
    }
   ]
  },
  {
   "title": "Влажность",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT\n    sm.generated_time AS \"time\",\n    coalesce(zd.friendly_name, sm.ieee_address) AS \"metric\",\n    (sm.data->'humidity')::float AS humidity\nFROM public.sensor_measurements AS sm\nLEFT JOIN devices_zigbeedevice zd on zd.ieee_address = sm.ieee_address\nWHERE $__timeFilter(sm.generated_time)\nORDER BY sm.generated_time ASC"
    }
   ]
  },
  {
   "title": "Батарея",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n    sm.generated_time AS \"time\",\n    coalesce(zd.friendly_name, sm.ieee_address) AS \"metric\",\n    (sm.data->>'battery')::float AS battery\nFROM public.sensor_measurements AS sm\nleft join devices_zigbeedevice zd on zd.ieee_address = sm.ieee_address\nWHERE $__timeFilter(sm.generated_time)\nORDER BY sm.generated_time ASC"
    }
   ]
  },
  {
   "title": "Качество связи",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n    sm.generated_time AS \"time\",\n    coalesce(zd.friendly_name, sm.ieee_address) AS \"metric\",\n    (sm.data->>'linkquality')::float AS linkquality\nFROM public.sensor_measurements AS sm\nleft join devices_zigbeedevice zd on zd.ieee_address = sm.ieee_address\nWHERE $__timeFilter(sm.generated_time)\nORDER BY sm.generated_time ASC"
    }
   ]
  }
 ]
}