# Generated by Django 4.2.28 on 2026-02-14 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeMarker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(help_text="Например: 'Начал отопление', 'Дрова прогорели', 'Включил электрообогреватель'", max_length=100, verbose_name='Краткое описание')),
                ('description', models.TextField(blank=True, help_text='Дополнительная информация о событии', verbose_name='Описание')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
