# Generated by Django 4.2.28 on 2026-02-14 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timemarkers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timemarker',
            options={'verbose_name': 'Веремнная метка', 'verbose_name_plural': 'Веремнные метки'},
        ),
    ]
