# Generated by Django 4.2.27 on 2026-02-08 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Например: 'Гостиная', 'Кухня', 'Этаж 1'", max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, help_text='Дополнительная информация о местоположении', verbose_name='Описание')),
                ('order', models.IntegerField(default=0, help_text='Чем меньше число, тем выше в списке (0 - самый верх)', verbose_name='Порядок сортировки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('parent', models.ForeignKey(blank=True, help_text='Выберите родительское местоположение для создания иерархии', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='locations.location', verbose_name='Родительское местоположение')),
            ],
            options={
                'verbose_name': 'Местоположение',
                'verbose_name_plural': 'Местоположения',
                'ordering': ['order', 'name'],
                'indexes': [models.Index(fields=['parent', 'order', 'name'], name='locations_l_parent__283a33_idx'), models.Index(fields=['order'], name='locations_l_order_fbf7bb_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(fields=('parent', 'name'), name='unique_location_name_per_parent', violation_error_message='Местоположение с таким именем уже существует на этом уровне'),
        ),
    ]
